# Generated by Django 5.0.2 on 2024-02-23 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transfer_timestamp_alter_transfer_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='receiver',
            new_name='receiver_account_no',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='sender',
            new_name='sender_account_no',
        ),
    ]
